apiVersion: v1
kind: Service
metadata:
  name: my-nginx-service
spec:
  selector:
    app: my-nginx
  type: NodePort  # Expose port on local. 
  ports:
  - protocol: TCP
    port: 80  # External Port
    targetPort: 80  # Port from container
    nodePort: 30080 #External Port to localhost acces
